# docker-compose.yml
version: "3.8"

services:
  nextjs:
    build: .
    container_name: greenr-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://greenradmin:greenradmin123@postgres:5444/greenr
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: always

  postgres:
    image: postgres:13
    container_name: greenr-db
    ports:
      - "5444:5444"
    environment:
      POSTGRES_USER: greenradmin
      POSTGRES_PASSWORD: greenradmin123
      POSTGRES_DB: greenr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
